# Generated by Django 4.1.5 on 2023-01-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_buku', models.CharField(max_length=100)),
                ('judul_buku', models.CharField(max_length=100)),
                ('penulis', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=100)),
                ('tahun_terbit', models.DateField()),
                ('jumlah_buku', models.IntegerField()),
            ],
        ),
    ]
